steps:
- name: gcr.io/cloud-builders/gsutil
  args:
    - 'cp'
    - 'gs://software.redpillanalytics.io/database/oracle-database-xe-18c-1.0-1.x86_64.rpm'
    - '12.2.1.4.0'
  id: copy-database
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/oxe
  - --cache=true
  - --cache-ttl=48h
  - --dockerfile=18.4.0/Dockerfile
  - --context=18.4.0
  id: kaniko-build
timeout: 3600s
