steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/oxe
  - --cache=true
  - --cache-ttl=48h
  - --dockerfile=18.4.0/Dockerfile
  - --context=18.4.0
  id: kaniko-build
timeout: 3600s
